Imports System.Drawing.Printing
Imports ADODB
Module Ent_Raw_Print
    Public PrintData As String

    Dim IsFirst As Boolean
    Dim DN As Date
    Dim pc As String
    Dim r_count As String
    Dim BIR_ID As String
    Dim IsLogin As Boolean
    Dim MaxR As String
    Dim MinR As String

    Public Sub Print(ByVal MSG As String)
        PrintData = PrintData & MSG & vbCrLf
    End Sub

    Public Sub Clear_PrintData()
        PrintData = vbNullString
    End Sub

    Public Enum ESC As Integer
        Defaul = 0
        Center = 1
        RightJ = 2
        LeftJ = 3
    End Enum

    Public Function ESC_COM(ByVal esc As ESC) As String
        Dim _center As String = Chr(27) & Chr(97) & Chr(esc)
        Return _center
    End Function

#Region "Print Stay IN"

    Public Sub PrintRaw_Now(ByVal Opname As String, ByVal OrasdtIn As Date, ByVal LogAdmin As String)

        Dim output As String = Chr(&H1D) & "V" & Chr(66) & Chr(0)
        Dim Line As String = "----------------------------------------"

        ' Print(ESC_COM(ESC.Center))
        Print(My.Settings.TITLE)
        Print(My.Settings.ADDR)
        Print(Line)
        Print("STAY IN REPORT")
        Print(Line)
        Print("Bussiness Date : " & My.Settings.BussDate)
        Print("Operator : " & Opname)
        Print("Generated By : " & LogAdmin)
        Print(Line)
        Print("STAY IN VEHICLES")
        Print(Line)

        Dim rs1 As New Recordset
        Dim lup As Long
        rs1 = New Recordset

        rs1 = conSqlPOS.Execute("select Plate,TimeIn from timeindb order by TimeIn")
        If rs1.EOF = False Then
            For lup = 1 To rs1.RecordCount
                '  Sleep(30)
                Print(rs1("Plate").Value & "   " & rs1("TimeIn").Value)
                rs1.MoveNext()
            Next
        End If

        Print(Line)
        Print("****** END OF REPORT ******")

        Print(output)

        _P(PrintData)

        Clear_PrintData()

    End Sub
#End Region

#Region "Print Receipt"
    Public Sub PrintReceiptRaw_Now()
        'On Error Resume Next
        ' Dim cd As New 'Company_Ref
        Dim OPname As String = "" 'Operator_Name
        Dim output As String = Chr(&H1D) & "V" & Chr(66) & Chr(0)
        Dim INiprinter As String = Chr(27) & Chr(64)
        Dim Line As String = "----------------------------------------"
        ' cd = Get_Comp()

        Print(ESC_COM(ESC.Center))
        Print(My.Settings.TITLE)
        Print(My.Settings.ADDR)
        'Print("AREA : " & cd.Company_LOC)
        Print("TIN# : " & P_TIN)
        Print("MS# : " & P_Machine)
        Print("SN# : " & P_Serial)
        Print("Terminal : " & P_Station)
        Print("CASHIER : " & P_Teller)
        Print(Line)

        Print("Official-Receipt # " & ESC_COM(ESC.RightJ) & P_ORno)
        Print(ESC_COM(ESC.Defaul))
        Print("CardCode       : " & P_CardCode)
        Print("Plate#         : " & P_PlateNo)
        Print("Vehicle        : " & P_Vehicle)
        Print("Time-in        : " & P_EntTime)
        Print("Time-Out       : " & P_ExtTime)
        Print("Time           : " & P_TotalTime)
        Print(Line)
        Print("COMPUTATION")
        ' ''Print("Regular        : P " & x.Regular)

        'If x.Overnight <> 0 Then Print("Overnight      : p " & x.Overnight)

        If P_Lost <> 0 Then Print("LostCard       : P" + " " + MakeMoney(P_Lost))



        'If CDbl(x.Compli) = 0 Then

        '    If x.CreditType = "-" Then
        '        Print("Cash           : P " & x.Cash)
        '    Else
        '        Print("Cash           : P " & x.Cash)
        '        Print("***" & x.CreditType & "****")
        '        Print("Reference-#    :   " & x.CreditCardRef)
        '        Print("AMT            : P " & x.Credit)
        '    End If

        'Else
        '    Print("Compliment    : P " & x.Compli)
        'End If

        'Print(vbNullString)
        Print("TOTAL          : " & " P " & MakeMoney(P_Total))
        Print("VAT-SALE       : " & " P " & MakeMoney(P_Vatable))
        Print("VAT-12%        : " & " P " & MakeMoney(P_Vat))
        'Print(Line)
        'Other_Print(x)
        Print(vbNullString)
        Print("Cash Tendered  : P " + MakeMoney(P_Tendered))
        Print("Change         : P " + MakeMoney(P_Change))

        Print(vbNullString)

        If ReceiptType = "Senior" Then
            Print("NAME OF SC/PWD: _______________________")
            Print("ADDRESS: ______________________________")
            Print("OSCA ID No./PWD ID No.: _______________")
            Print("TIN: __________________________________")
            Print("SC/PWD Signature: _____________________")
        Else
            Print("NAME OF PARKER: _______________________")
            Print("ADDRESS: ______________________________")
            Print("TIN: __________________________________")
        End If


        'Print("Name of Parker:_________________________________")
        'Print("Address:________________________________________")
        'Print("TIN:____________________________________________")

        Print(ESC_COM(ESC.Center))

        Print(Line)
        Print("Integrated Security and Automation Inc.")
        Print("210 N.Domingo St. cor. Araneta Ave San Juan City")
        Print("VAT Reg. TIN : 006-593-714-000")
        Print(" ")
        Print("ACCR# : " & P_ACCR)
        Print("ACCR Date : " & Format(My.Settings.N_AccrDate, "yyyy-MM-dd"))
        Print("PERMIT : " & P_Permit)
        Print("Permit Date Effective : " & Format(My.Settings.N_PermitDateIssued, "yyyy-MM-dd"))
        Print(Line)

        Print("THIS OFFICIAL RECEIPT SHALL BE VALID FOR")
        Print("5 YEARS FROM THE DATE OF")
        Print("THE PERMIT TO USE")
        Print(output)

        'Print("CASHIER : " & OPname)

        _P(PrintData)

        Clear_PrintData()

    End Sub
#End Region

#Region "Print Cashier Logout"
    Public Sub printCAshierRaw(ByVal Opname As String, ByVal BussDt As Date)

        OperatorName = Opname
        'UserPangalan = Usernem
        BussPetsa = BussDt
        'PetsaDtout = OrasdtOut

        'frmSummRep.picLoading.Visible = True
        'Print the receipt text
        Dim output As String = Chr(&H1D) & "V" & Chr(66) & Chr(0)

        Print(My.Settings.TITLE)
        Print(My.Settings.ADDR)
        Print(" Contact No.: " & My.Settings.CONTACT)
        Print(" Permit #: " & My.Settings.PERMIT)
        Print(" TIN : " & My.Settings.TIN)
        Print(" Accr #: " & My.Settings.ACCR)
        Print(" Machine #:" & My.Settings.MACHINE)
        Print(" SN #:" & My.Settings.SERIAL)
        'Print("___________________________________________________________________________")
        Print("----------------------------------------")
        Print("OPERATOR'S  LOG-OUT  REPORT")
        Print("----------------------------------------")

        Dim strOp As String = OperatorName
        Dim strStation As String = frmMain.txtStation.Text

        Dim time1 As Date = DtinFrm(strOp, strStation, BussPetsa)
        Dim time2 As Date = DtOutTo(strOp, strStation, BussPetsa)

        Dim FromOr As String = OrFrom(strOp, strStation, BussPetsa)
        Dim ToOr As String = OrTo(strOp, strStation, BussPetsa)

        Dim VipTotalCnt As Integer = VipOutCount(time1, time2) + VipInOutCount(time1, time2)
        Dim TotalTrans As Integer = TotalTR(strOp, strStation, BussPetsa)
        Dim TotalGraceCnt As Integer = 0
        Dim TotalGraceCntM As Integer = 0
        Dim TotalLostCnt As Integer = 0
        Dim TotalTrCount As Integer = 0
        Dim TotalRetail As Integer = 0
        Dim TotalMotor As Integer = 0

        Dim TotalManual As Integer = 0

        Dim NetSale As Double = TotalNet(strOp, strStation, BussPetsa)
        Dim VatAmt As Double = VAT(NetSale)
        Dim VatSale As Double = Comp_Vat_sale(NetSale, VatAmt)
        Dim TotalPartialCash As Double = PartialCashOut(BussPetsa, strOp)
        Dim TotalCash As Double = DiffSaleCashOut(NetSale, TotalPartialCash)


        Print("Time From : " & Format(time1, "yyyy-MM-dd HH:mm:00"))
        Print("Time To : " & Format(time2, "yyyy-MM-dd HH:mm:00"))
        Print("Operator : " & strOp)
        Print("Station : " & strStation)
        Print("From ORno :" & FromOr)
        Print("To ORno :" & ToOr)

        Print("----------------------------------------")
        Print("Transaction Summary")
        Print("----------------------------------------")


        Dim strBussDate As String = Format(BussPetsa, "yyyy-MM-dd")

        Dim rsVeh As New Recordset
        rsVeh = New Recordset

        rsVeh = conSqlPOS.Execute("select VehicleType from tblcharge")

        If rsVeh.EOF = False Then
            Dim VehTyp As String
            Do While rsVeh.EOF = False
                VehTyp = rsVeh("VehicleType").Value
                Dim rs1 As New Recordset
                rs1 = New Recordset

                rs1 = conSqlPOS.Execute("select VehicleCount from vwegracecount where VehicleType = '" & VehTyp & "' and Station = '" & strStation & "' and Operator = '" & strOp & "' and BussDate = '" & strBussDate & "' limit 1;")
                If rs1.EOF = False Then
                    TotalGraceCnt = TotalGraceCnt + Val(rs1("VehicleCount").Value)
                    If Val(rs1("VehicleCount").Value) <> 0 Then
                        Print("GP " & VehTyp & " " & rs1("VehicleCount").Value & " P 0.00")
                    End If
                End If

                rsVeh.MoveNext()
            Loop
        End If

        Print("VIP " & VipTotalCnt & " P 0.00")

        Dim rs As New Recordset
        rs = New Recordset

        rs = conSqlPOS.Execute("select VehicleCount,VehicleType,VehicleTotalAmt from vwevehsumcount where Station = '" & strStation & "' and Paytype <> 'GracePeriod' and Paytype <> 'Manual' and Operator = '" & strOp & "' and LostCard = 0 and BussDate like '" & strBussDate & "%';")
        Do While rs.EOF = False
            TotalRetail = TotalRetail + Val(rs("VehicleCount").Value)
            Print(rs("VehicleType").Value & " " & rs("VehicleCount").Value & " P " & MakeMoney(rs("VehicleTotalAmt").Value))
            rs.MoveNext()
        Loop

        Dim rs2 As New Recordset
        rs2 = New Recordset

        rs2 = conSqlPOS.Execute("select LostCount,LostAmt from vwelostcount where Station = '" & strStation & "' and Operator = '" & strOp & "' and BussDate like '" & strBussDate & "%'")
        Do While rs2.EOF = False
            TotalLostCnt = rs2("LostCount").Value
            If TotalLostCnt = 0 Then
                Print("LOST CARD" & " " & TotalLostCnt & " P 0.00")
            Else
                Print("LOST CARD" & " " & TotalLostCnt & " P " & MakeMoney(Val(rs2("LostAmt").Value)))
            End If
            rs2.MoveNext()
        Loop

        Dim rs3 As New Recordset
        rs3 = New Recordset

        rs3 = conSqlPOS.Execute("select ManCount,ManAmt from vwemanualsumcount where PayType = 'Manual' and Station = '" & strStation & "' and Operator = '" & strOp & "' and BussDate like '" & strBussDate & "%'")
        Do While rs3.EOF = False
            TotalManual = rs3("ManCount").Value
            If TotalManual = 0 Then
                Print("MANUAL INPUT" & " " & TotalLostCnt & " P 0.00")
            Else
                Print("MANUAL INPUT" & " " & TotalLostCnt & "P " & MakeMoney(Val(rs3("ManAmt").Value)))
            End If
            rs3.MoveNext()
        Loop

        Print("----------------------------------------")

        TotalTrCount = TotalTrans + VipTotalCnt
        Print("Total Transaction : " & TotalTrCount)

        Print("----------------------------------------")


        Print("Total Sales :" & " P" + " " + MakeMoney(NetSale))

        Print("Partial Cash Out :" & " P" + " " + MakeMoney(TotalPartialCash))

        Print("Total Cash :" & " P" + " " + MakeMoney(TotalCash))

        Print("Total VAT :" & " P" + " " + MakeMoney(VatAmt))

        Print("Total VAT Sales :" & " P" + " " + MakeMoney(VatSale))

        Print("Signature : ____________________________")

        Print("****** END OF REPORT ******")

        Print("                     ")
        Print("                     ")

        Print(output)
        _P(PrintData)

    End Sub
#End Region

#Region "Print Station Logout"
    Public Sub printStationRaw(ByVal dtFrm As Date, ByVal dtTo As Date)
        ShiftFrm = dtFrm
        ShiftTo = dtTo

        Dim output As String = Chr(&H1D) & "V" & Chr(66) & Chr(0)

        Print(My.Settings.TITLE)
        Print(My.Settings.ADDR)
        Print(" Contact No.: " & My.Settings.CONTACT)
        Print(" Permit #: " & My.Settings.PERMIT)
        Print(" TIN : " & My.Settings.TIN)
        Print(" Accr #: " & My.Settings.ACCR)
        Print(" Machine #:" & My.Settings.MACHINE)
        Print(" SN #:" & My.Settings.SERIAL)

        Print("----------------------------------------")
        Print("STATION'S  LOG-OUT  REPORT")
        Print("----------------------------------------")

        Dim strStation As String = frmMain.txtStation.Text

        Dim FromOr As String = sOrFrom(strStation)
        Dim ToOr As String = sOrTo(strStation)

        Dim NetSale As Double = sTotalNet(strStation)
        Dim VatAmt As Double = VAT(NetSale)
        Dim VatSale As Double = Comp_Vat_sale(NetSale, VatAmt)

        Print("Bussines Date : " & Format(My.Settings.BussDate, "yyyy-MM-dd"))

        Print("Time From : " & Format(Format(ShiftFrm, "yyyy-MM-dd HH:mm:ss")))
        Print("Time To : " & Format(Format(ShiftTo, "yyyy-MM-dd HH:mm:ss")))
        Print("Station : " & strStation)
        Print("From ORno : " & FromOr)
        Print("To ORno : " & ToOr)

        Print("----------------------------------------")
        Print("Cashier Summary")
        Print("----------------------------------------")

        Dim strBussDate As String = Format(PetsaBuss, "yyyy-MM-dd")
        Dim strFrm As String = Format(ShiftFrm, "yyyy-MM-dd HH:mm:00")
        Dim strTo As String = Format(ShiftTo, "yyyy-MM-dd HH:mm:59")
        'Dim strTime2 As String = Format(time2, "yyyy-MM-dd HH:mm:ss")
        Dim rs As New Recordset
        rs = New Recordset

        rs = conSqlPOS.Execute("select Operator,Count(Operator)as OpCount,sum(total)as OpTotalAmt from tblincomereport where Station = '" & strStation & "' and TimeOut >= '" & strFrm & "' and  TimeOut <= '" & strTo & "' group by Operator")
        Do While rs.EOF = False
            Dim kahera As String = rs("Operator").Value
            Dim TotalbyKahera As Double = rs("OpTotalAmt").Value
            Dim time1 As Date = SDtinFrm(kahera, strStation)
            Dim time2 As Date = SDtOutTo(kahera, strStation)

            Print("Cashier : " & kahera)
            Print("Time From : " & time1)
            Print("Time To : " & time2)
            Print("Cashier Total Sales : " & "P " & MakeMoney(TotalbyKahera))
            Print("                     ")

            rs.MoveNext()
        Loop

        Print("----------------------------------------")
        Print("Transaction Summary")
        Print("----------------------------------------")

        Dim TotalTrans As Integer = sTotalTR(strStation)
        Dim VipTotalCnt As Integer = VipOutCount(ShiftFrm, ShiftTo) + VipInOutCount(ShiftFrm, ShiftTo)
        Dim TotalGraceCnt As Integer = 0
        Dim TotalGraceCntM As Integer = 0
        Dim TotalLostCnt As Integer = 0
        Dim TotalTrCount As Integer = 0
        Dim TotalRetail As Integer = 0
        Dim TotalMotor As Integer = 0
        Dim TotalManual As Integer = 0


        Dim rsVeh As New Recordset
        rsVeh = New Recordset

        rsVeh = conSqlPOS.Execute("select VehicleType from tblcharge")

        If rsVeh.EOF = False Then
            Dim VehTyp As String
            Do While rsVeh.EOF = False
                VehTyp = rsVeh("VehicleType").Value
                Dim rs1 As New Recordset
                rs1 = New Recordset

                rs1 = conSqlPOS.Execute("select Count(VehicleType)as VehicleCount from tblincomereport where PayType = 'GracePeriod' and VehicleType = '" & VehTyp & "' and Station = '" & strStation & "' and TimeOut >= '" & strFrm & "' and  TimeOut <= '" & strTo & "'")
                Do While rs1.EOF = False
                    TotalGraceCnt = TotalGraceCnt + Val(rs1("VehicleCount").Value)
                    If Val(rs1("VehicleCount").Value) <> 0 Then
                        Print("GP " & VehTyp & " " & rs1("VehicleCount").Value & " P 0.00")
                    End If
                    rs1.MoveNext()
                Loop
                rsVeh.MoveNext()
            Loop
        End If

        Print("VIP " & VipTotalCnt & " P 0.00")

        Dim rs3 As New Recordset
        rs3 = New Recordset

        rs3 = conSqlPOS.Execute("select VehicleType,Count(VehicleType)as VehicleCount,sum(total)as VehicleTotalAmt from tblincomereport where Station = '" & strStation & "' and PayType <> 'GracePeriod' and PayType <> 'Manual' and LostCard = 0 and TimeOut >= '" & strFrm & "' and  TimeOut <= '" & strTo & "' group by VehicleType")
        Do While rs3.EOF = False
            TotalRetail = TotalRetail + Val(rs3("VehicleCount").Value)
            Print(rs3("VehicleType").Value & " " & rs3("VehicleCount").Value & "P " & MakeMoney(rs3("VehicleTotalAmt").Value))
            rs3.MoveNext()
        Loop

        Dim rs2 As New Recordset
        rs2 = New Recordset

        rs2 = conSqlPOS.Execute("select Count(LostCard)as LostCount,Sum(total) as LostAmt from tblincomereport where LostCard > 0 and Station = '" & strStation & "' and TimeOut >= '" & strFrm & "' and  TimeOut <= '" & strTo & "'")
        Do While rs2.EOF = False
            TotalLostCnt = rs2("LostCount").Value

            If TotalLostCnt = 0 Then
                Print("LOST CARD" & " " & TotalLostCnt & " P 0.00")
            Else
                Print("LOST CARD" & " " & TotalLostCnt & " P " & MakeMoney(rs2("LostAmt").Value))
            End If
            rs2.MoveNext()
        Loop

        Dim rs4 As New Recordset
        rs4 = New Recordset

        rs4 = conSqlPOS.Execute("select Count(PayType)as ManCount,Sum(total) as ManAmt from tblincomereport where PayType = 'Manual' and Station = '" & strStation & "' and TimeOut >= '" & strFrm & "' and  TimeOut <= '" & strTo & "'")
        Do While rs4.EOF = False

            TotalManual = rs4("ManCount").Value

            If TotalManual = 0 Then
                Print("MANUAL INPUT " & TotalManual & " P 0.00")
            Else
                Print("MANUAL INPUT " & TotalManual & " P " & MakeMoney(Val(rs4("ManAmt").Value)))
            End If
            rs4.MoveNext()
        Loop


        Print("----------------------------------------")

        TotalTrCount = TotalGraceCnt + VipTotalCnt + TotalLostCnt + TotalRetail + TotalMotor + TotalGraceCntM + TotalManual
        Print("Total Transaction : " & TotalTrCount)

        Print("----------------------------------------")

        Print("Total Sales :" & " P" + " " + MakeMoney(NetSale))

        Print("Total VAT :" & " P" + " " + MakeMoney(VatAmt))

        Print("Total VAT Sales :" & " P" + " " + MakeMoney(VatSale))

        Print("Signature : _______________________________")

        Print("****** END OF REPORT ******")

        Print("                     ")
        Print("                     ")

        Print(output)
        _P(PrintData)

    End Sub
#End Region

#Region "Print Z Read"
    Sub ZreadRaw(ByVal zreaddt As Date)
       
      

        Dim output As String = Chr(&H1D) & "V" & Chr(66) & Chr(0)

        Print(My.Settings.TITLE)
        Print(My.Settings.ADDR)
        Print(" Contact No.: " & My.Settings.CONTACT)
        Print(" Permit #: " & My.Settings.PERMIT)
        Print(" TIN : " & My.Settings.TIN)
        Print(" Accr #: " & My.Settings.ACCR)
        Print(" Machine #:" & My.Settings.MACHINE)
        Print(" SN #:" & My.Settings.SERIAL)

        Print("----------------------------------------")
        Print("Z-READING REPORT")
        Print("----------------------------------------")

        Dim rs As New Recordset
        Dim Scon As String = vbNullString
        Dim Ops As String = vbNullString
        Dim a As String = Format(zreaddt, "yyyy-MM-dd")
        ' DN = Format(strlastEOD, "yyyy-MM-dd HH:mm:ss")

        Print("Report Date : " & a)
        Print("Station : " & frmMain.txtStation.Text)
        Print("Operator : " & frmMain.TxtOp.Text)

        Dim TNS As String = vbNullString
        MinR = vbNullString
        MinR = frmZreport.GetMinOR(a, frmMain.txtStation.Text, "ORno")
        MaxR = vbNullString
        MaxR = frmZreport.GetMaxOR(a, frmMain.txtStation.Text, "ORno")
        Dim cnt As Integer = frmZreport.GET_TRcnt(a)
        Dim NetSale As Double = frmZreport.GET_GTNEW(a, "Total")
        Dim NetVat As Double = frmZreport.Get_Vat(NetSale)
        Dim NewNetVatSale As Double = frmZreport.Get_SubTotal(NetSale, NetVat)
        Dim OldSale As Double = frmZreport.GT_OLD(a, "Total")
        Dim NewSale As Double = NetSale + OldSale
        Dim NewVat As Double = frmZreport.Get_Vat(NewSale)
        Dim NewVatSale As Double = frmZreport.Get_SubTotal(NewSale, NewVat)

        Print("OR From : " & MinR)
        Print("OR To : " & MaxR)
        Print("Total Transaction : " & cnt)
        TNS = "Php " & MakeMoney(NetSale)
        Print("Total NET-Sales : " & TNS)
        TNS = "Php " & MakeMoney(NewNetVatSale)
        Print("Total 12% VAT-Sales : " & TNS)
        TNS = "Php " & MakeMoney(NetVat)
        Print("Total Gross Sales : " & TNS)
        Print("          ")

        TNS = "Php " & MakeMoney(OldSale)
        Print("Old Accumulated Sales : " & TNS)
        TNS = "Php " & MakeMoney(NewSale)
        Print("New Accumulated Sales : " & TNS)
        TNS = "Php " & MakeMoney(NewVatSale)
        Print("Grand Total 12% VAT Sales : " & TNS)
        TNS = "Php " & MakeMoney(NewVat)
        Print("Total Gross : " & TNS)


        Print("                     ")
        Print("----------- End of Report -----------")


        frmZreport.savelast(a, NetSale)

        Print("                     ")
        Print("                     ")

        Print(output)
        _P(PrintData)

    End Sub
#End Region
End Module
