'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost")>  _
        Public Property DB_IP1() As String
            Get
                Return CType(Me("DB_IP1"),String)
            End Get
            Set
                Me("DB_IP1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property DB_User1() As String
            Get
                Return CType(Me("DB_User1"),String)
            End Get
            Set
                Me("DB_User1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_Pass1() As String
            Get
                Return CType(Me("DB_Pass1"),String)
            End Get
            Set
                Me("DB_Pass1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cpposdb")>  _
        Public Property DB_Db1() As String
            Get
                Return CType(Me("DB_Db1"),String)
            End Get
            Set
                Me("DB_Db1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_IP2() As String
            Get
                Return CType(Me("DB_IP2"),String)
            End Get
            Set
                Me("DB_IP2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property DB_User2() As String
            Get
                Return CType(Me("DB_User2"),String)
            End Get
            Set
                Me("DB_User2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_Pass2() As String
            Get
                Return CType(Me("DB_Pass2"),String)
            End Get
            Set
                Me("DB_Pass2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cpposdb")>  _
        Public Property DB_Db2() As String
            Get
                Return CType(Me("DB_Db2"),String)
            End Get
            Set
                Me("DB_Db2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DEV_con() As String
            Get
                Return CType(Me("DEV_con"),String)
            End Get
            Set
                Me("DEV_con") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PrinterDriver() As String
            Get
                Return CType(Me("PrinterDriver"),String)
            End Get
            Set
                Me("PrinterDriver") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_Sport() As String
            Get
                Return CType(Me("DB_Sport"),String)
            End Get
            Set
                Me("DB_Sport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_LPort() As String
            Get
                Return CType(Me("DB_LPort"),String)
            End Get
            Set
                Me("DB_LPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("378")>  _
        Public Property PortAdd() As String
            Get
                Return CType(Me("PortAdd"),String)
            End Get
            Set
                Me("PortAdd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255")>  _
        Public Property Port() As String
            Get
                Return CType(Me("Port"),String)
            End Get
            Set
                Me("Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property Delay() As String
            Get
                Return CType(Me("Delay"),String)
            End Get
            Set
                Me("Delay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CAM_IP() As String
            Get
                Return CType(Me("CAM_IP"),String)
            End Get
            Set
                Me("CAM_IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CAM_Port() As Integer
            Get
                Return CType(Me("CAM_Port"),Integer)
            End Get
            Set
                Me("CAM_Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CAM_User() As String
            Get
                Return CType(Me("CAM_User"),String)
            End Get
            Set
                Me("CAM_User") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CAM_Pass() As String
            Get
                Return CType(Me("CAM_Pass"),String)
            End Get
            Set
                Me("CAM_Pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CAM_ChannelEnt() As Integer
            Get
                Return CType(Me("CAM_ChannelEnt"),Integer)
            End Get
            Set
                Me("CAM_ChannelEnt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CAM_ChannelCap1() As Integer
            Get
                Return CType(Me("CAM_ChannelCap1"),Integer)
            End Get
            Set
                Me("CAM_ChannelCap1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CAM_ChannelExt() As Integer
            Get
                Return CType(Me("CAM_ChannelExt"),Integer)
            End Get
            Set
                Me("CAM_ChannelExt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CAM_ChannelCap2() As Integer
            Get
                Return CType(Me("CAM_ChannelCap2"),Integer)
            End Get
            Set
                Me("CAM_ChannelCap2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PD_Com() As String
            Get
                Return CType(Me("PD_Com"),String)
            End Get
            Set
                Me("PD_Com") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TIN() As String
            Get
                Return CType(Me("TIN"),String)
            End Get
            Set
                Me("TIN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PERMIT() As String
            Get
                Return CType(Me("PERMIT"),String)
            End Get
            Set
                Me("PERMIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SERIAL() As String
            Get
                Return CType(Me("SERIAL"),String)
            End Get
            Set
                Me("SERIAL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MACHINE() As String
            Get
                Return CType(Me("MACHINE"),String)
            End Get
            Set
                Me("MACHINE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ACCR() As String
            Get
                Return CType(Me("ACCR"),String)
            End Get
            Set
                Me("ACCR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Station 1")>  _
        Public Property STATION() As String
            Get
                Return CType(Me("STATION"),String)
            End Get
            Set
                Me("STATION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SLOT() As String
            Get
                Return CType(Me("SLOT"),String)
            End Get
            Set
                Me("SLOT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HOURLY")>  _
        Public Property MODE() As String
            Get
                Return CType(Me("MODE"),String)
            End Get
            Set
                Me("MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2013-12-23")>  _
        Public Property BussDate() As Date
            Get
                Return CType(Me("BussDate"),Date)
            End Get
            Set
                Me("BussDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LogoPath() As String
            Get
                Return CType(Me("LogoPath"),String)
            End Get
            Set
                Me("LogoPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property OR_Number() As Integer
            Get
                Return CType(Me("OR_Number"),Integer)
            End Get
            Set
                Me("OR_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TITLE() As String
            Get
                Return CType(Me("TITLE"),String)
            End Get
            Set
                Me("TITLE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ADDR() As String
            Get
                Return CType(Me("ADDR"),String)
            End Get
            Set
                Me("ADDR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CONTACT() As String
            Get
                Return CType(Me("CONTACT"),String)
            End Get
            Set
                Me("CONTACT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("63")>  _
        Public Property LoopCode() As String
            Get
                Return CType(Me("LoopCode"),String)
            End Get
            Set
                Me("LoopCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("379")>  _
        Public Property StatAdd() As String
            Get
                Return CType(Me("StatAdd"),String)
            End Get
            Set
                Me("StatAdd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DesktopLock() As Boolean
            Get
                Return CType(Me("DesktopLock"),Boolean)
            End Get
            Set
                Me("DesktopLock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DataPool() As Boolean
            Get
                Return CType(Me("DataPool"),Boolean)
            End Get
            Set
                Me("DataPool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ServerPing() As Boolean
            Get
                Return CType(Me("ServerPing"),Boolean)
            End Get
            Set
                Me("ServerPing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2019-09-03")>  _
        Public Property HourlyCut() As Date
            Get
                Return CType(Me("HourlyCut"),Date)
            End Get
            Set
                Me("HourlyCut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2019-09-03")>  _
        Public Property FlatCut() As Date
            Get
                Return CType(Me("FlatCut"),Date)
            End Get
            Set
                Me("FlatCut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BussAuto() As Boolean
            Get
                Return CType(Me("BussAuto"),Boolean)
            End Get
            Set
                Me("BussAuto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property GPprint() As Boolean
            Get
                Return CType(Me("GPprint"),Boolean)
            End Get
            Set
                Me("GPprint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2013-12-23")>  _
        Public Property SaleCutt() As Date
            Get
                Return CType(Me("SaleCutt"),Date)
            End Get
            Set
                Me("SaleCutt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SumRawPrint() As Boolean
            Get
                Return CType(Me("SumRawPrint"),Boolean)
            End Get
            Set
                Me("SumRawPrint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Company Operating")>  _
        Public Property N_OperatedBy() As String
            Get
                Return CType(Me("N_OperatedBy"),String)
            End Get
            Set
                Me("N_OperatedBy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("POS Vendor Company")>  _
        Public Property N_PosVendor() As String
            Get
                Return CType(Me("N_PosVendor"),String)
            End Get
            Set
                Me("N_PosVendor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("POS Vendor Company Address")>  _
        Public Property N_PosVendorAddr() As String
            Get
                Return CType(Me("N_PosVendorAddr"),String)
            End Get
            Set
                Me("N_PosVendorAddr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("POSVendor TIN")>  _
        Public Property N_PosVendorTin() As String
            Get
                Return CType(Me("N_PosVendorTin"),String)
            End Get
            Set
                Me("N_PosVendorTin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000-01-21")>  _
        Public Property N_AccrDate() As Date
            Get
                Return CType(Me("N_AccrDate"),Date)
            End Get
            Set
                Me("N_AccrDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property N_PermitDateIssued() As Date
            Get
                Return CType(Me("N_PermitDateIssued"),Date)
            End Get
            Set
                Me("N_PermitDateIssued") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ctrl_TriggerDelay() As UInteger
            Get
                Return CType(Me("ctrl_TriggerDelay"),UInteger)
            End Get
            Set
                Me("ctrl_TriggerDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_SN() As String
            Get
                Return CType(Me("ctrl_SN"),String)
            End Get
            Set
                Me("ctrl_SN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_Ip() As String
            Get
                Return CType(Me("ctrl_Ip"),String)
            End Get
            Set
                Me("ctrl_Ip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_Port() As String
            Get
                Return CType(Me("ctrl_Port"),String)
            End Get
            Set
                Me("ctrl_Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_Mac() As String
            Get
                Return CType(Me("ctrl_Mac"),String)
            End Get
            Set
                Me("ctrl_Mac") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_Subnet() As String
            Get
                Return CType(Me("ctrl_Subnet"),String)
            End Get
            Set
                Me("ctrl_Subnet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_Gateway() As String
            Get
                Return CType(Me("ctrl_Gateway"),String)
            End Get
            Set
                Me("ctrl_Gateway") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ctrl_PcIp() As String
            Get
                Return CType(Me("ctrl_PcIp"),String)
            End Get
            Set
                Me("ctrl_PcIp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_svr2IP() As String
            Get
                Return CType(Me("DB_svr2IP"),String)
            End Get
            Set
                Me("DB_svr2IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property DB_svr2UID() As String
            Get
                Return CType(Me("DB_svr2UID"),String)
            End Get
            Set
                Me("DB_svr2UID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DB_svr2PWD() As String
            Get
                Return CType(Me("DB_svr2PWD"),String)
            End Get
            Set
                Me("DB_svr2PWD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cpposdb")>  _
        Public Property DB_svr2DB() As String
            Get
                Return CType(Me("DB_svr2DB"),String)
            End Get
            Set
                Me("DB_svr2DB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ServerMode() As Boolean
            Get
                Return CType(Me("ServerMode"),Boolean)
            End Get
            Set
                Me("ServerMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SINGLE")>  _
        Public Property Operation() As String
            Get
                Return CType(Me("Operation"),String)
            End Get
            Set
                Me("Operation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ActiCode() As String
            Get
                Return CType(Me("ActiCode"),String)
            End Get
            Set
                Me("ActiCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrialStart() As String
            Get
                Return CType(Me("TrialStart"),String)
            End Get
            Set
                Me("TrialStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrialDays() As String
            Get
                Return CType(Me("TrialDays"),String)
            End Get
            Set
                Me("TrialDays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LOPrint() As Boolean
            Get
                Return CType(Me("LOPrint"),Boolean)
            End Get
            Set
                Me("LOPrint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property KickCashDrawer() As Boolean
            Get
                Return CType(Me("KickCashDrawer"),Boolean)
            End Get
            Set
                Me("KickCashDrawer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("THANK YOU FOR")>  _
        Public Property PDwelcome1() As String
            Get
                Return CType(Me("PDwelcome1"),String)
            End Get
            Set
                Me("PDwelcome1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PARKING!")>  _
        Public Property PDwelcome2() As String
            Get
                Return CType(Me("PDwelcome2"),String)
            End Get
            Set
                Me("PDwelcome2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BIR BASED")>  _
        Public Property POS_VER() As String
            Get
                Return CType(Me("POS_VER"),String)
            End Get
            Set
                Me("POS_VER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ZRead_Cnt() As Long
            Get
                Return CType(Me("ZRead_Cnt"),Long)
            End Get
            Set
                Me("ZRead_Cnt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OvSucceeding() As Boolean
            Get
                Return CType(Me("OvSucceeding"),Boolean)
            End Get
            Set
                Me("OvSucceeding") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CardDataBckup() As Boolean
            Get
                Return CType(Me("CardDataBckup"),Boolean)
            End Get
            Set
                Me("CardDataBckup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EntryLogDb() As Boolean
            Get
                Return CType(Me("EntryLogDb"),Boolean)
            End Get
            Set
                Me("EntryLogDb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Er302Com() As Integer
            Get
                Return CType(Me("Er302Com"),Integer)
            End Get
            Set
                Me("Er302Com") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CarParkPOS.My.MySettings
            Get
                Return Global.CarParkPOS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
